version: '3'

services:
  app:
    container_name: 'server_transaksi'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=3008
    ports:
      - "8090:3008"
    command: bash -c "npm install cookie-parser && npm start"
    networks:
      - backend_network

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - "8005:8005"

  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /usr/share/nginx/html:/usr/share/nginx/html
  #     - /var/www/html:/var/www/html
  #   networks:
  #     - backend_network

volumes:
  node_modules:

networks:
  backend_network:
    driver: bridge
