version: '3.8'

services:
  app:
    container_name: 'backend_overnight'
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /shared/upload_on/uploads:/app/uploads
    environment:
      - PORT=3002
    ports:
      - "8090:3002"
    networks:
      - backend_network

volumes:
  node_modules:

networks:
  backend_network:
    driver: bridge
