version: '3.3'

services:
  app:
    container_name: 'server_transaksi'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8000:8000
    stdin_open: true
    environment:
      - PORT=8000
    command: npm run start
volumes:
  node_modules:      