version: '3.3'

services:
  app:
    container_name: 'server_transaksi'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=3001
    command: npm run start
    networks:
      - backend_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "82:82"
      - "83:83"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/www/html:/var/www/html
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
