version: '3.8'

services:
  app:
    container_name: 'server_transaksi'
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
      - shared/upload_on:/app/uploads
    environment:
      - PORT=3008
    ports:
      - "8090:3008"
    # command: npm install cookie-parser && npm start
    networks:
      - bridge
  
# volumes:
#   node_modules:

# networks:
#   backend_network:
#     driver: bridge
