version: '3.9'

services:
  app:
    container_name: 'backend_occ'
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /shared/upload_on/uploads:/app/uploads
    environment:
      - PORT=3002
    ports:
      - "8090:3002"
    networks:
      - backend_command_center
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  node_modules:

networks:
  backend_command_center:
    driver: bridge
