#register users
###
POST http://localhost:3008/v01/member/api/auth/register
Content-Type: application/json
# https://dev-valetapi.skyparking.online
{
    "username":"tomy21",
    "email":"tomy21.agung@gmail.com",
    "phone":"+628921233427",
    "password":"123456",
    "pin":"321321"
}


#register users
###
POST http://localhost:3008/v01/member/api/auth/login
Content-Type: application/json

{
    "identifier":"newTenant01",
    "password":"sky123",
    "rememberMe":true
}

#getUserById
###
GET http://localhost:3008/v01/member/api/auth/user
Content-Type: application/json

#getUserById
###
PATCH  http://localhost:3008/v01/member/api/auth/user/24
Content-Type: application/json

{
  "Pin":"321321"
}

#getUserByIdDetail
###
POST http://localhost:3008/v01/member/api/auth/verifikasi
Content-Type: application/json

{
  "MemberUserId" : 30,
  "Pin":"123123"
}


#getProduct
###
GET http://localhost:3008/v01/member/api/product?page=1&limit=5
Content-Type: application/json

#getProductById
###
GET http://localhost:3008/v01/member/api/product/1
Content-Type: application/json

#UpdatedProductById
###
PATCH http://localhost:3008/v01/member/api/product/1
Content-Type: application/json

{
    "MaxQuote": 1000
}

#getByLocations
###
GET http://localhost:3008/v01/member/api/product/byLocation?LocationCode=004SK
Content-Type: application/json

#DeleteProductById
###
DELETE http://localhost:3008/v01/member/api/product/5
Content-Type: application/json

#CreatedProduct
###
POST http://localhost:3008/v01/member/api/product
Content-Type: application/json

{
    "ProductName": "Product 1",
    "ProductDescription": "Description of Product B",
    "VehicleType": "Mobil",
    "DateActive": "2024-08-31T23:59:59.999Z",
    "MaxQuote": 100,
    "isDeleted": "0",
    "LocationCode": "004SK",
    "LocationName": "UNIVERSITAS PELITA HARAPAN"
}


# Member Provider
###
# Create Payment Gateway
###
POST http://localhost:3008/v01/member/api/listProvider
Content-Type: application/json

{
    "ProviderName": "Bank ABC",
    "Description": "Payment gateway for Bank ABC",
    "ChannelId": "ABC123",
    "BankId": "ABC456",
    "PartnerServiceId": "ABC789",
    "LogoUrl": "http://example.com/logo.png"
}

# Get All Payment Gateways
###
GET http://localhost:3008/v01/member/api/listProvider
Content-Type: application/json

###
GET http://localhost:3008/v01/member/api/listProvider/list?isOpen=1
Content-Type: application/json

# Get Payment Gateway By ID
###
GET http://localhost:3008/v01/member/api/listProvider/1
Content-Type: application/json

# Update Payment Gateway By ID
###
PATCH http://localhost:3008/v01/member/api/listProvider/2
Content-Type: application/json

{
    "Description": "Updated description for Bank ABC"
}

# Soft Delete Payment Gateway By ID
###
DELETE http://localhost:3008/v01/member/api/listProvider/1
Content-Type: application/json


# UserMemberProduct
###
# Get all MemberUserProducts
GET http://localhost:3008/v01/member/api/userProduct
Content-Type: application/json

###
# Get all MemberUserProducts
GET http://localhost:3008/v01/member/api/userProduct/verifikasi?platNo=B0987PPI
Content-Type: application/json

###
# Get a single MemberUserProduct by ID
GET http://localhost:3008/v01/member/api/userProduct/byUser?userId=21
Content-Type: application/json

###
# Get a single MemberUserProduct by ID
GET http://localhost:3008/v01/member/api/userProduct/2
Content-Type: application/json


###
# Create a new MemberUserProduct
POST http://localhost:3008/v01/member/api/userProduct
Content-Type: application/json

{
  "CardId": "123456787",
  "RfId": "987654327",
  "PlateNumber": "B1234ABC",
  "IsUsed": 0,
  "MemberUserId": 22
}

###

# Update a MemberUserProduct by ID
PATCH http://localhost:3008/v01/member/api/userProduct/4
Content-Type: application/json

{
  "TypeVehicle": "Motor"
}

###

# Soft delete a MemberUserProduct by ID
DELETE http://localhost:3008/v01/member/api/userProduct/1
Content-Type: application/json

{
  "DeletedBy": "admin"
}


# history Transactions
###
# Get all MemberHistoryTransactions
GET http://localhost:3008/v01/member/api/memberHistoryTransactions
Content-Type: application/json

###

# Get a single MemberHistoryTransaction by ID
GET http://localhost:3008/v01/member/api/memberHistoryTransactions/1
Content-Type: application/json

###

# Get a single MemberHistoryTransaction by UserID
GET http://localhost:3008/v01/member/api/memberHistory/users?userId=21
Content-Type: application/json

###

# Create a new MemberHistoryTransaction
POST http://localhost:3008/v01/member/api/memberHistoryTransactions
Content-Type: application/json

{
  "IdUsers": 30,
  "LocationName": "-",
  "Activity": "topup",
  "Price": 25000,
  "Status": "Paid",
  "CreatedBy": "system"
}

###
# Get a single MemberUserProduct by ID
GET http://localhost:3008/v01/member/api/trxhistories
Content-Type: application/json

# request location
###
GET http://localhost:3008/api/getByLocationAll?page=1&limit=10


### 
# Get all MemberProductBundles
GET http://localhost:3008/v01/member/api/memberProductBundles
Content-Type: application/json

### 
# Get all MemberProductBundles
GET http://localhost:3008/v01/member/api/products/type/Mobil
Content-Type: application/json

###
# Create a new MemberProductBundle
POST http://localhost:3008/v01/member/api/memberProductBundles
Content-Type: application/json

{
  "Name": "1 Bulan Agustus",
  "StartDate": "2024-08-01T00:00:00.000Z",
  "EndDate": "2024-08-31T23:59:59.000Z",
  "IsDeleted": false,
  "Price": 300000.00,
  "CardActivateFee": 50000.00,
  "Type": "Mobil",
  "Fee": 5000.00,
  "TrxMemberQuoteId": 19,
  "CreateBy": "Admin"
}

###
# Get a single MemberProductBundle by ID
GET http://localhost:3008/v01/member/api/memberProductBundles/23
Content-Type: application/json

###
# Update a MemberProductBundle by ID
PUT http://localhost:3008/v01/member/api/memberProductBundles/20
Content-Type: application/json

{
  "Name": "Updated Bundle Name",
  "StartDate": "2024-08-04T00:00:00.000Z",
  "EndDate": "2024-12-31T23:59:59.000Z",
  "IsDeleted": false,
  "Price": 300000.00,
  "CardActivate": 50000.00
}

###
# Delete a MemberProductBundle by ID
DELETE http://localhost:3008/v01/member/api/memberProductBundles/1
Content-Type: application/json


# Tenant API Requeest
### 

###
# Get all MemberTenants with pagination
GET http://localhost:3008/v01/member/api/tenant?page=1&limit=10
Content-Type: application/json

###
# Get a single MemberTenant by ID
GET http://localhost:3008/v01/member/api/tenant/1
Content-Type: application/json

###
# Create a new MemberTenant
POST http://localhost:3008/v01/member/api/tenant
Content-Type: application/json

{
  "Name": "New Tenant 1",
  "UserName": "newTenant01",
  "Description": "Description for new tenant",
  "Email": "marvin.johannes@skyparking.co.id",
  "Password":"sky123",
  "PhoneNumber": "1234567890",
  "Pin": "123456",
  "Address": "123 Main St",
  "City": "CityName",
  "Region": "RegionName",
  "PostalCode": "12345",
  "Country": "CountryName",
  "Fax": "1234567890",
  "CreatedBy": "Admin"
}

###
# Update a MemberTenant by ID
PATCH http://localhost:3008/v01/member/api/tenant/1
Content-Type: application/json

{
  "Name": "Updated Tenant Name",
  "Description": "Updated Description",
  "Email": "updatedemail@example.com",
  "PhoneNumber": "0987654321",
  "Address": "456 Another St",
  "City": "NewCity",
  "Region": "NewRegion",
  "PostalCode": "54321",
  "Country": "NewCountry",
  "Fax": "0987654321",
  "UpdatedBy": "Admin"
}

###
# Delete a MemberTenant by ID
DELETE http://localhost:3008/v01/member/api/tenant/1
Content-Type: application/json




# TRX Member Payment
###
# Get all TrxMemberPayments with pagination
GET http://localhost:3008/v01/member/api/payments?page=1&limit=10
Content-Type: application/json

###
# Get a single TrxMemberPayment by ID
GET http://localhost:3008/v01/member/api/payments/92
Content-Type: application/json

###
# Get a single TrxMemberPayment by ID
GET http://localhost:3008/v01/member/api/paymentStatus/213332319739011688
Content-Type: application/json

###
# Create a new TrxMemberPayment
POST http://localhost:3008/v01/member/api/payments
Content-Type: application/json

{
  "Type": "Credit",
  "PartnerServiceId": "PS123456",
  "CustomerNo": "CUST001",
  "VirtualAccountNo": "VA00123456789",
  "VirtualAccountName": "John Doe",
  "VirtualAccountEmail": "john.doe@example.com",
  "TrxId": "TRX123456789012",
  "InquiryRequestId": "INQREQ1234567890",
  "PaymentRequestId": "PAYREQ1234567890",
  "PaymentFlagStatus": "01",
  "ExpiredDate": "2024-08-31T23:59:59.000Z",
  "TrxDateTime": "2024-08-05T10:00:00.000Z",
  "TransactionDate": "2024-08-05T10:00:00.000Z",
  "ReferenceNo": "REF123456",
  "JournalNum": "JN001",
  "FlagAdvise": "Y",
  "IsDeleted": 0,
  "TrxMemberTotalAmountId": 1,
  "TrxMemberPaidAmountId": 1,
  "TrxMemberAdditionalInfoId": 1,
  "MemberUserProductId": 1
}

###
# Update a TrxMemberPayment by ID
PATCH http://localhost:3008/v01/member/api/payments/1
Content-Type: application/json

{
  "Type": "Debit",
  "PartnerServiceId": "PS654321",
  "CustomerNo": "CUST002",
  "VirtualAccountNo": "VA9876543210",
  "VirtualAccountName": "Jane Doe",
  "VirtualAccountEmail": "jane.doe@example.com",
  "TrxId": "TRX098765432109",
  "InquiryRequestId": "INQREQ0987654321",
  "PaymentRequestId": "PAYREQ0987654321",
  "PaymentFlagStatus": "02",
  "ExpiredDate": "2024-09-30T23:59:59.000Z",
  "TrxDateTime": "2024-09-05T10:00:00.000Z",
  "TransactionDate": "2024-09-05T10:00:00.000Z",
  "ReferenceNo": "REF654321",
  "JournalNum": "JN002",
  "FlagAdvise": "N",
  "IsDeleted": 1,
  "TrxMemberTotalAmountId": 2,
  "TrxMemberPaidAmountId": 2,
  "TrxMemberAdditionalInfoId": 2,
  "MemberUserProductId": 2
}

###
# Delete a TrxMemberPayment by ID
DELETE http://localhost:3008/v01/member/api/payments/1
Content-Type: application/json


# member transaction tenants
### Create a new tempTransactionMemberTenant
POST http://localhost:3008/v01/member/api/transactionTenants
Content-Type: application/json

{
  "OrderId": "ORD123",
  "TenantName": "Tenant A",
  "LocationCode": "LOC001",
  "LocationName": "Location A",
  "QuotaMember": 10,
  "Price": 500.00,
  "RecordStatus": "Active",
  "CreatedBy": "Admin"
}

### Get all transactionTenants
GET http://localhost:3008/v01/member/api/transactionTenants

### Get a tempTransactionMemberTenant by ID
GET http://localhost:3008/v01/member/api/transactionTenants/1

### Update a tempTransactionMemberTenant
PATCH http://localhost:3008/v01/member/api/transactionTenants/1
Content-Type: application/json

{
  "OrderId": "ORD124",
  "TenantName": "Tenant B",
  "LocationCode": "LOC002",
  "LocationName": "Location B",
  "QuotaMember": 20,
  "Price": 700.00,
  "RecordStatus": "Inactive",
  "UpdatedBy": "Admin"
}

### Delete a tempTransactionMemberTenant
DELETE http://localhost:3008/v01/member/api/transactionTenants/1


###
# Get a single MemberProductBundle by ID
GET http://localhost:3008/v01/member/api/quota/1
Content-Type: application/json