###
GET https://dev-valetapi.skyparking.online/v01/occ/api/gates/2

###
GET http://localhost:3008/v01/occ/api/gates?page=1&limit=&search=10

###
PUT https://dev-valetapi.skyparking.online/v01/occ/api/gates/2
Content-Type: application/json

{
    "arduino": "1"
}

###
PUT http://localhost:3008/v01/occ/api/gates/2
Content-Type: application/json

{
    "statusGate": 1
}