GET http://localhost:3008/api/getUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI5LCJuYW1lIjoidmFsZXQgMyIsImVtYWlsIjoidjNAZ21haWwuY29tbiIsImlhdCI6MTcxNzA0MTIwNywiZXhwIjoxNzE3MDQxMjIyfQ.mykYvJq8APz0NjOCO-NG57Dq2pGOrXOa9cztD-NKdhA

###
POST http://localhost:3008/api/login
Content-Type: application/json

{
    "data":"U2FsdGVkX1+I/xlyIYVi3V9/tGU/qzT+mf9DvtMG1eoZPCvzFdKSk4h6WgmYYt0HO9/USuuMjr/yWu4EFDAqwA=="
}

###
GET http://localhost:3008/api/token
###
GET http://localhost:3008/api/logout
###
GET http://localhost:3008/api/getByLocation?userId=102


# request location
###
GET http://147.139.135.195:8090/api/getAllLocation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY3LCJuYW1lIjoidGVzdDEiLCJlbWFpbCI6InRlc3RAZW1haWwudGVzdCIsImlhdCI6MTcxNDc1OTE0NiwiZXhwIjoxNzE0NzU5MTYxfQ.4yQZGJf_EKRU79YuApY6BgSa7QAG6ZDBysZ75llcXrA


# request Issuer
###
GET http://localhost:3008/api/getAllIssuer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY3LCJuYW1lIjoidGVzdDEiLCJlbWFpbCI6InRlc3RAZW1haWwudGVzdCIsImlhdCI6MTcxNTA3MDc5OSwiZXhwIjoxNzE1MDcwODE0fQ.SuhTdSq6CFjht0w1oYhk9FkSqACPB_BttKgFC0u3cG0

#register users
###
POST http://localhost:3008/api/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI5LCJuYW1lIjoidmFsZXQgMyIsImVtYWlsIjoidjNAZ21haWwuY29tbiIsImlhdCI6MTcxNjg4OTc5NSwiZXhwIjoxNzE2ODg5ODEwfQ.aSKrtTl5_I86g9OOJPCwEzVOVMmDW_57j0JwCJSsFog
Content-Type: application/json

{
    "SetupRoleId": 14,
    "IpAddress": "192.168.43.201",
    "Name": "Dede elv R1",
    "Gender": "M",
    "Username": "DedeElvR1",
    "Email": "dedeElvR1@testing.com",
    "Phone": "XXXXXXX",
    "MerchantId": 0,
    "IsFirstpassword":0,
    "LocationCode": ["ELVSK"]
}



