GET http://localhost:3008/api/getUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MjksImVtYWlsIjoidjNAZ21haWwuY29tbiIsImlhdCI6MTcyNDk1NzQxNywiaXNzIjoiaHR0cHM6Ly9za3lwYXJraW5nLm9ubGluZSIsInN1YiI6IkFkbWluVmFsZXQzIiwiZXhwIjoxNzI1MDQzODE3fQ.DVMNXZfVfXeQsR_uet9QjXgPXeyDu43VL6rgufoAKMA

###
POST http://localhost:3008/api/login
Content-Type: application/json

{
    "identifier":"v3@gmail.comn",
    "password":"sky123"
}

###
GET http://localhost:3008/api/token
###
GET http://localhost:3008/api/logout
###
GET http://localhost:3008/api/getByLocation?userId=114

###
GET http://localhost:3008/api/getAllLocation


# request location
###
GET http://localhost:3008/api/getByLocationAll
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY3LCJuYW1lIjoidGVzdDEiLCJlbWFpbCI6InRlc3RAZW1haWwudGVzdCIsImlhdCI6MTcxNDc1OTE0NiwiZXhwIjoxNzE0NzU5MTYxfQ.4yQZGJf_EKRU79YuApY6BgSa7QAG6ZDBysZ75llcXrA


# request Issuer
###
GET http://localhost:3008/api/getAllOverNightApps?location=08SKY
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MjksImVtYWlsIjoidjNAZ21haWwuY29tbiIsImlhdCI6MTcyNDk0MjQ2MywiaXNzIjoiaHR0cHM6Ly9za3lwYXJraW5nLm9ubGluZSIsInN1YiI6IkFkbWluVmFsZXQzIiwiZXhwIjoxNzI1MDI4ODYzfQ.G2tVkUV95Yi2WtGNpdPeJxMT8nJ55qFjhyuEPLgBuvE

#register users
###
POST http://localhost:3008/api/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI5LCJuYW1lIjoidmFsZXQgMyIsImVtYWlsIjoidjNAZ21haWwuY29tbiIsImlhdCI6MTcxNjg4OTc5NSwiZXhwIjoxNzE2ODg5ODEwfQ.aSKrtTl5_I86g9OOJPCwEzVOVMmDW_57j0JwCJSsFog
Content-Type: application/json

{
    "SetupRoleId": 14,
    "IpAddress": "192.168.43.201",
    "Name": "Ilvan",
    "Gender": "M",
    "Username": "ilvan.beverly",
    "Email": "ilvan.beverly@testing.com",
    "Phone": "XXXXXXX",
    "MerchantId": 0,
    "IsFirstpassword":0,
    "FlagAllLocation":0,
    "LocationCode": ["014SK"]
}

#register users
###
POST http://localhost:3008/v01/member/api/auth/register
Content-Type: application/json

{
    "username":"tomy21",
    "email":"tomy21.agung@gmail.com",
    "phone":"+628921211111",
    "password":"123456",
    "pin":"321321"
}


#register users
###
POST http://localhost:3008/v01/member/api/auth/login
Content-Type: application/json

{
    "identifier":"tomy21",
    "password":"123456",
    "rememberMe":true
}



